# Create 1D Array

In [2]:
import numpy

i = numpy.array([10, 20, 30, 40, 50])

print(i)

[10 20 30 40 50]


# Create 2D Array

In [3]:
import numpy

i = numpy.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print(i)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


# Create 3D Array

In [4]:
import numpy

i = numpy.array([
    [[10, 20, 30], [11,22,33]],
    [[40, 50, 60], [44,55,66]],
    [[70, 80, 90], [77,88,99]]
])

print(i)

[[[10 20 30]
  [11 22 33]]

 [[40 50 60]
  [44 55 66]]

 [[70 80 90]
  [77 88 99]]]


# Alias in Numpy / Alternative Names

In [5]:
import numpy as np

i = np.array([10, 20, 30, 40, 50])

print(i)

[10 20 30 40 50]


# Check Numpy Version

In [6]:
import numpy as np

print(np.__version__)

1.18.1


# Type Function- Use to Check Data Type

In [8]:
import numpy as np

i = np.array([10, 20, 30, 40, 50, 60])

print(i)

print(type(i))

j = 10

print(type(j))

[10 20 30 40 50 60]
<class 'numpy.ndarray'>
<class 'int'>


# Create Numpy Array with Tuple Values

In [9]:
import numpy as np

i = np.array((10, 20, 30, 40, 50, 60))

print(i)

[10 20 30 40 50 60]


# Check Array Dimensions

In [13]:
import numpy as np

i = np.array([
    [[10, 20, 30], [40, 50, 60]], 
    [[11, 22, 33], [44, 55,66]]
])

print("No. of dimensions is ", i.ndim)

No. of dimensions is  3


# Define the Number of Dimensions

In [15]:
import numpy as np

i = np.array([10, 20, 30, 40], ndmin=5)

print(i)
print()
print(i.ndim)

[[[[[10 20 30 40]]]]]

5


# Access Elements in Numpy

In [17]:
import numpy as np

i = np.array([10, 20, 30, 40, 50])

print(i[0])  # Access element by Index values, Index always start from 0

10


In [19]:
import numpy as np
i = np.array([
    [10,20,30,40,50],    # main index 0  sub index 0 1 2 3 4
    [60,70,80,90,100]    # main index 1  sub index 0 1 2 3 4
])

print(i[1, 1])

70


In [20]:
import numpy as np

i = np.array([
    [10,20,30,40,50],    # main index 0  sub index 0 1 2 3 4
    [60,70,80,90,100]    # main index 1  sub index 0 1 2 3 4
])

print(i[0, 4])

50


In [22]:
import numpy as np

i= np.array([
    [[10, 20, 30], [40, 50, 60]],      # 0 - 0 1 - 0 1 2
    [[70, 80, 90], [100, 110, 120]]    # 1 - 0 1 - 0 1 2
])

print(i[0, 1, 2])

60


In [24]:
import numpy as np

arr = np.array([
    [[10, 20, 30], [40, 50, 60]],    # 0 - 0 1 - 0 1 2
    [[70, 80, 90], [100, 110, 120]]  # 1 - 0 1 - 0 1 2
])

print(arr[1, 1, 2])

120


In [25]:
import numpy as np

arr = np.array([
    [[10, 20, 30], [40, 50, 60]],    # 0 - 0 1 - 0 1 2
    [[70, 80, 90], [100, 110, 120]]  # 1 - 0 1 - 0 1 2
])

print(arr[1, 1, -1])

120


In [26]:
import numpy as np

arr = np.array([
    [[10, 20, 30], [40, 50, 60]],    # 0 - 0 1 - 0 1 2
    [[70, 80, 90], [100, 110, 120]]  # 1 - 0 1 - 0 1 2
])

print(arr[1, -2, -1])

90
